shopping_list = ["meat","cheese"]
print("\tWelcome to the Grocery Shopping List App\n ")
#Mostramos la fecha y la hora
import datetime
time = datetime.datetime.now()
month = str(time.month)
day = str(time.day)
hour = str(time.hour)
minute =str(time.minute)
print("The time is " , month,"/",day," ",hour,":",minute ,"\n")
#Añadimos los productos a la lista de compra
print("you currently have ",shopping_list[0]," and ", shopping_list[1],"on your grocery list")
food = input("what more grocery would you like to add: ").lower()
food1 = input("what more grocery would you like to add: ").lower()
food2 = input("what more grocery would you like to add: ").lower()
shopping_list.append(food)
shopping_list.append(food1)
shopping_list.append(food2)
print(shopping_list)
print(sorted(shopping_list))
print("\nSimulating grocery shopping...\n")
print("Current grocery list: ",len(shopping_list)," items")
print(sorted(shopping_list))
#Retiramos los productos a vender de la lista
m = input("What food did you just buy: ").lower()
print("Removing ",m.capitalize()," from list")
shopping_list.remove(m)
print("Current grocery list: ",len(shopping_list)," items")
print(sorted(shopping_list))
n = input("What food did you just buy: ").lower()
print("Removing ", n.capitalize(),"from list")
shopping_list.remove(n)
print("Curent grocery list: ",len(shopping_list)," items")
print(sorted(shopping_list))
c = input("What food did you just buy: ").lower()
print("Removing ", c.capitalize(),"from list")
shopping_list.remove(c)
print("Curent grocery list: ",len(shopping_list)," items")
print(sorted(shopping_list))
print("\nSorry, the store is out of ",sorted(shopping_list)[1].capitalize())
#Ya que no hay carne, removemos la variable 'meat' y la intercambiamos por 'fish'
shopping_list.remove('meat')
food3 = input("What food would you like instead: ").lower()
print("\nHere is what remains on your grocery list: ")
shopping_list.append(food3)
print(shopping_list)